apiVersion: v1
kind: Service
metadata:
  name: oficina-app-service
  namespace: default
  labels:
    app: oficina-app
spec:
  type: ClusterIP
  selector:
    app: oficina-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
